### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by dinhtrung** [dinhtrung/smpptools#1]
- [ ] Post("/api/base-sms", api.CreateBaseSmUsingPOST)
- [ ] Delete("/api/base-sms/:id", api.DeleteBaseSmUsingDELETE)
- [ ] Get("/api/base-sms", api.GetAllBaseSmsUsingGET)
- [ ] Get("/api/base-sms/:id", api.GetBaseSmUsingGET)
- [ ] Patch("/api/base-sms/:id", api.PartialUpdateBaseSmUsingPATCH)
- [ ] Put("/api/base-sms/:id", api.UpdateBaseSmUsingPUT)

- [ ] Delete("/api/esme-accounts/:id/batch", api.ApiEsmeAccountsIdBatchDelete)
- [ ] Post("/api/esme-accounts", api.CreateEsmeAccountUsingPOST)
- [ ] Delete("/api/esme-accounts/:id", api.DeleteEsmeAccountUsingDELETE)
- [ ] Get("/api/esme-accounts", api.GetAllEsmeAccountsUsingGET)
- [ ] Get("/api/esme-accounts/:id", api.GetEsmeAccountUsingGET)
- [ ] Patch("/api/esme-accounts/:id", api.PartialUpdateEsmeAccountUsingPATCH)
- [ ] Post("/api/esme-accounts/:id/send-mt", api.SendMobileTerminatedSMSOnAccountUsingPOST)
- [ ] Post("/api/esme-accounts/:id/batch", api.SendSMSonSMSCsessionUsingPOST)
- [ ] Delete("/api/esme-accounts/:id/stop-all", api.StopAllEsmeSessionsForAccountUsingDELETE)
- [ ] Put("/api/esme-accounts/:id", api.UpdateEsmeAccountUsingPUT)
- [ ] Post("/api/esme-sessions", api.CreateEsmeSessionUsingPOST)
- [ ] Delete("/api/esme-sessions/:sessionID", api.DeleteEsmeSessionUsingDELETE)
- [ ] Get("/api/esme-sessions", api.GetAllEsmeSessions)
- [ ] Get("/api/esme-sessions/:sessionID", api.GetEsmeSessionUsingGET)
- [ ] Patch("/api/esme-sessions/:sessionID", api.PartialUpdateEsmeSessionUsingPATCH)
- [ ] Post("/api/esme-sessions/:id/batch", api.SendSMSonEsmeSessionUsingPOST)
- [ ] Delete("/api/esme-sessions/:id/batch", api.StopAllBachOnEsmeSessionUsingDELETE)
- [ ] Put("/api/esme-sessions/:sessionID", api.UpdateEsmeSessionUsingPUT)
- [ ] Post("/api/isdn-lists", api.CreateIsdnListUsingPOST)
- [ ] Delete("/api/isdn-lists/:id", api.DeleteIsdnListUsingDELETE)
- [ ] Get("/api/isdn-lists", api.GetAllIsdnListsUsingGET)
- [ ] Get("/api/isdn-lists/:id", api.GetIsdnListUsingGET)
- [ ] Patch("/api/isdn-lists/:id", api.PartialUpdateIsdnListUsingPATCH)
- [ ] Put("/api/isdn-lists/:id", api.UpdateIsdnListUsingPUT)
- [ ] Post("/api/smsc-accounts", api.CreateSmscAccountUsingPOST)
- [ ] Delete("/api/smsc-accounts/:id", api.DeleteSmscAccountUsingDELETE)
- [ ] Get("/api/smsc-accounts", api.GetAllSmscAccountsUsingGET)
- [ ] Get("/api/smsc-accounts/:id", api.GetSmscAccountUsingGET)
- [ ] Patch("/api/smsc-accounts/:id", api.PartialUpdateSmscAccountUsingPATCH)
- [ ] Post("/api/smsc-accounts/:id/send-mo", api.SendMobileOriginatedSMSOnAccountUsingPOST)
- [ ] Delete("/api/smsc-accounts/:id/stop-all", api.StopAllSessionsForSmscAccountUsingDELETE)
- [ ] Put("/api/smsc-accounts/:id", api.UpdateSmscAccountUsingPUT)

// + smsc-instances
- [ ] Post("/api/smsc-instances", api.CreateSmscInstanceUsingPOST)
- [ ] Delete("/api/smsc-instances/:instanceID", api.DeleteSmscInstanceUsingDELETE)
- [ ] Get("/api/smsc-instances", api.GetAllSmscInstancesUsingGET)
- [ ] Get("/api/smsc-instances/:instanceID", api.GetSmscInstanceUsingGET)
- [ ] Patch("/api/smsc-instances/:instanceID", api.PartialUpdateSmscInstanceUsingPATCH)
- [ ] Post("/api/smsc-instances/:instanceID/batch", api.StartBatchOnSmscInstanceUsingPOST)
- [ ] Get("/api/smsc-instances/:instanceID/start", api.StartSmscInstanceUsingGET)
- [ ] Delete("/api/smsc-instances/:instanceID/batch", api.StopAllBatchSmscInstanceUsingDELETE)
- [ ] Delete("/api/smsc-instances/:instanceID/stop", api.StopSmscInstanceUsingDELETE)
- [ ] Put("/api/smsc-instances/:instanceID", api.UpdateSmscInstanceUsingPUT)

- [ ] Delete("/api/smsc-sessions/:id/batch", api.ApiSmscSessionsIdBatchDelete)
- [ ] Delete("/api/smsc-sessions/:id/stop", api.ApiSmscSessionsIdStopDelete)
- [ ] Delete("/api/smsc-sessions/:id", api.DeleteSmscSessionUsingDELETE)
- [ ] Get("/api/smsc-sessions", api.GetAllSmscSessions)
- [ ] Get("/api/smsc-sessions/:id", api.GetSmscSessionUsingGET)
- [ ] Patch("/api/smsc-sessions/:id", api.PartialUpdateSmscSessionUsingPATCH)
- [ ] Post("/api/smsc-sessions/:id/send-mo", api.SendMobileOriginatedSMSUsingPOST)
- [ ] Post("/api/smsc-sessions/:id/batch", api.SendSMSonSmscSessionUsingPOST)
- [ ] Put("/api/smsc-sessions/:id", api.UpdateSmscSessionUsingPUT)
- [ ] Post("/api/throughput-series", api.CreateThroughputSeriesUsingPOST)
- [ ] Delete("/api/throughput-series/:id", api.DeleteThroughputSeriesUsingDELETE)
- [ ] Get("/api/throughput-series", api.GetAllThroughputSeriessUsingGET)
- [ ] Get("/api/throughput-series/:id", api.GetThroughputSeriesUsingGET)
- [ ] Get("/api/throughput-series/:id/transform/{variantID}", api.GetVariantThroughputSeriesUsingGET)
- [ ] Patch("/api/throughput-series/:id", api.PartialUpdateThroughputSeriesUsingPATCH)
- [ ] Put("/api/throughput-series/:id", api.UpdateThroughputSeriesUsingPUT)
